# Generated by Django 5.2.4 on 2025-07-07 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes_subareas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Subárea',
                'verbose_name_plural': 'Subáreas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes_tipos_personagem', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tipo de personagem',
                'verbose_name_plural': 'Tipos de personagem',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vantagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='qualidade')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('pontuacao', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('arvore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='antecedentes.vantagem', verbose_name='árvore')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes_vantagens', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('sub_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='antecedentes.subarea', verbose_name='subárea')),
                ('tipo_personagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='antecedentes.tipopersonagem', verbose_name='tipo de personagem')),
            ],
            options={
                'verbose_name': 'Vantagem',
                'verbose_name_plural': 'Vantagens',
                'ordering': ['nome'],
            },
        ),
    ]
