# Generated by Django 5.2.4 on 2025-07-07 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npc', '0001_initial'),
        ('vampiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='idade')),
                ('pais', models.CharField(max_length=200, verbose_name='país')),
                ('estado', models.CharField(max_length=200, verbose_name='estado')),
                ('origem_nome', models.TextField(verbose_name='origem do nome')),
                ('historia', models.TextField(blank=True, null=True, verbose_name='história')),
                ('historia_sobrenatural', models.TextField(blank=True, null=True, verbose_name='história sobrenatural')),
                ('populacao', models.IntegerField(blank=True, null=True, verbose_name='população')),
                ('populacao_sobrenatural', models.IntegerField(blank=True, null=True, verbose_name='população sobrenatural')),
                ('eventos', models.TextField(blank=True, null=True, verbose_name='eventos')),
                ('eventos_sobrenaturais', models.TextField(blank=True, null=True, verbose_name='eventos sobrenaturais')),
                ('clima', models.TextField(max_length=400, verbose_name='clima')),
                ('atmosfera', models.TextField(max_length=400, verbose_name='atmosfera')),
                ('arquitetura', models.TextField(max_length=400, verbose_name='arquitetura')),
                ('economia', models.TextField(verbose_name='economia')),
                ('religiao', models.TextField(verbose_name='religiao')),
                ('religiao_sobrenatural', models.TextField(verbose_name='religiao sobrenatural')),
                ('mobilidade', models.TextField(verbose_name='mobilidade')),
                ('ruas_principais', models.TextField(verbose_name='ruas principais')),
                ('locais_proibidos', models.TextField(verbose_name='locais proibidos')),
                ('bairros_elegantes', models.TextField(verbose_name='bairros elegantes')),
                ('bairros_decadentes', models.TextField(verbose_name='bairros decadentes')),
                ('centros_comerciais', models.TextField(verbose_name='centros comerciais')),
                ('centros_culturais', models.TextField(verbose_name='centros culturais')),
                ('zonas_perifericas', models.TextField(verbose_name='zonas periféricas')),
                ('zonas_rurais', models.TextField(verbose_name='zonas rurais')),
                ('prefeito', models.CharField(blank=True, max_length=200, null=True, verbose_name='prefeito')),
                ('controle_prefeito', models.TextField(blank=True, null=True, verbose_name='controle prefeito')),
                ('detalhes_prefeitura', models.TextField(verbose_name='detalhes prefeitura')),
                ('orgaos_publicos', models.TextField(verbose_name='orgaos publicos')),
                ('delegacias', models.TextField(verbose_name='delegacias')),
                ('policiais', models.TextField(verbose_name='policiais')),
                ('detalhes_policiais', models.TextField(verbose_name='detalhes policiais')),
                ('esgotos', models.TextField(verbose_name='esgotos')),
                ('detalhes_esgotos', models.TextField(verbose_name='detalhes esgotos')),
                ('hospitais', models.TextField(verbose_name='hospitais')),
                ('detalhes_hospitais', models.TextField(verbose_name='detalhes hospitais')),
                ('bibliotecas', models.TextField(verbose_name='bibliotecas')),
                ('detalhes_bibliotecas', models.TextField(verbose_name='detalhes bibliotecas')),
                ('parques', models.TextField(verbose_name='parques')),
                ('detalhes_parques', models.TextField(verbose_name='detalhes parques')),
                ('museus', models.TextField(verbose_name='museus')),
                ('detalhes_museus', models.TextField(verbose_name='detalhes museus')),
                ('midias', models.TextField(verbose_name='midias')),
                ('detalhes_midias', models.TextField(verbose_name='detalhes midias')),
                ('aeroporto', models.TextField(verbose_name='aeroporto')),
                ('empresas', models.TextField(verbose_name='empresas')),
                ('detalhes_empresas', models.TextField(verbose_name='detalhes empresas')),
                ('locais_importantes', models.TextField(verbose_name='locais importantes')),
                ('abrigos', models.TextField(verbose_name='abrigos')),
                ('universidades', models.TextField(verbose_name='universidades')),
                ('gangues', models.TextField(verbose_name='gangues')),
                ('vida_noturna', models.TextField(verbose_name='vida noturna')),
                ('descricao_cortes', models.TextField(verbose_name='descricao cortes')),
                ('senescal', models.TextField(verbose_name='senescal')),
                ('primigenie', models.TextField(verbose_name='primigênie')),
                ('secretarios_clas', models.TextField(verbose_name='secretários clãs')),
                ('xerifes', models.TextField(verbose_name='xerifes')),
                ('arauto', models.TextField(verbose_name='arauto')),
                ('elisios', models.TextField(verbose_name='elisíos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cidades_relacionadas', models.ManyToManyField(blank=True, to='cidade.cidade', verbose_name='cidades relacionadas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('npcs', models.ManyToManyField(blank=True, related_name='cidade_npcs', to='npc.npc', verbose_name='Npcs')),
                ('vampiros', models.ManyToManyField(blank=True, related_name='cidade_vampiros', to='vampiro.vampiro', verbose_name='Vampiros')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('pontuacao', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidade_notas', to='cidade.cidade', verbose_name='Cidade')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades_nota', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['nome'],
            },
        ),
    ]
